<?php

use MapasCulturais\i;

$payment_bank_data = [
    'payment_social_type' => [
        'label' => 'Tipo social',
        'type' => 'select',
        'options' => [
            1 => i::__('Pessoa física'),
            2 => i::__('Pessoa jurídica'),
        ],
        'validations' => [
            'required' => i::__("O Tipo social é obrigatório")
        ]
    ],

    'payment_proponent_name' => [
        'label' => i::__('Nome do proponente'),
        'type' => 'string',
        'validations' => [
            'required' => i::__("O nome do proponente é obrigatório")
        ]
    ],

    'payment_proponent_document' => [
        'label' => i::__('Documento do proponente'),
        'type' => 'string',
        'field_type' => 'fieldMask',
        'validations' => [
            'required' => i::__("O documento obrigatório"),
            'v::oneOf(v::cpf(), v::cnpj())' => i::__("O número do documento é inválido"),
        ]
    ],

    'payment_account_type' =>  [
        'label' => i::__('Tipo de conta'),
        'type' => 'select',
        'options' => [
            1 => i::__('Conta corrente'),
            2 => i::__('Conta poupança'),
        ],
        'validations' => [
            'required' => i::__("O tipo de conta obrigatório")
        ]
    ],

    'payment_bank' =>  [
        'label' => i::__('Banco'),
        'type' => 'select',
        'options' => [
            '1' => i::__("Banco Do Brasil S.A (BB) - 1"),
            '237' => i::__("Bradesco S.A - 237"),
            '260' => i::__("Nu Pagamentos S.A (Nubank) - 260"),
            '290' => i::__("Pagseguro Internet S.A - 290"),
            '323' => i::__("Mercado Pago – Conta Do Mercado - 323"),
            '341' => i::__("Itaú Unibanco S.A - 341"),
            '104' => i::__("Caixa Econômica Federal (CEF) - 104"),
            '33'  => i::__("Banco Santander Brasil S.A - 33"),
            '212' => i::__("Banco Original S.A - 212"),
            '422' => i::__("Banco Safra S.A - 422"),
            '745' => i::__("Banco Citibank S.A - 745"),
            '4'   => i::__("Banco Do Nordeste Do Brasil S.A. - 4"),
            '7'   => i::__("Bndes (Banco Nacional Do Desenvolvimento Social) - 7"),
            '117' => i::__("Advanced Cc Ltda - 117"),
            '172' => i::__("Albatross Ccv S.A - 172"),
            '188' => i::__("Ativa S.A Investimentos - 188"),
            '280' => i::__("Avista S.A - 280"),
            '80'  => i::__("B&T Cc Ltda - 80"),
            '654' => i::__("Banco A.J. Renner S.A - 654"),
            '246' => i::__("Banco Abc Brasil S.A - 246"),
            '121' => i::__("Banco Agibank S.A - 121"),
            '25'  => i::__("Banco Alfa S.A. - 25"),
            '641' => i::__("Banco Alvorada S.A - 641"),
            '65'  => i::__("Banco Andbank S.A - 65"),
            '96'  => i::__("Banco B3 S.A - 96"),
            '36'  => i::__("Banco Bbi S.A - 36"),
            '47'  => i::__("Banco Bco Do Estado De Sergipe S.A - 47"),
            '250' => i::__("Banco Bcv - 250"),
            '318' => i::__("Banco Bmg S.A - 318"),
            '107' => i::__("Banco Bocom Bbm S.A - 107"),
            '63'  => i::__("Banco Bradescard - 63"),
            '122' => i::__("Banco Bradesco Berj S.A - 122"),
            '204' => i::__("Banco Bradesco Cartoes S.A - 204"),
            '394' => i::__("Banco Bradesco Financiamentos S.A - 394"),
            '218' => i::__("Banco Bs2 S.A - 218"),
            '208' => i::__("Banco Btg Pactual S.A - 208"),
            '336' => i::__("Banco C6 S.A – C6 Bank - 336"),
            '473' => i::__("Banco Caixa Geral Brasil S.A - 473"),
            '412' => i::__("Banco Capital S.A - 412"),
            '40'  => i::__("Banco Cargill S.A - 40"),
            '320' => i::__("Banco Ccb Brasil S.A - 320"),
            '266' => i::__("Banco Cedula S.A - 266"),
            '739' => i::__("Banco Cetelem S.A - 739"),
            '233' => i::__("Banco Cifra - 233"),
            '241' => i::__("Banco Classico S.A - 241"),
            '95'  => i::__("Banco Confidence De Câmbio S.A - 95"),
            '222' => i::__("Banco Crédit Agricole Br S.A - 222"),
            '505' => i::__("Banco Credit Suisse (Brl) S.A - 505"),
            '69'  => i::__("Banco Crefisa S.A - 69"),
            '3'   => i::__("Banco Da Amazonia S.A - 3"),
            '83'  => i::__("Banco Da China Brasil S.A - 83"),
            '707' => i::__("Banco Daycoval S.A - 707"),
            '70'  => i::__("Banco De Brasília (Brb) - 70"),
            '335' => i::__("Banco Digio S.A - 335"),
            '37'  => i::__("Banco Do Estado Do Pará S.A - 37"),
            '196' => i::__("Banco Fair Cc S.A - 196"),
            '265' => i::__("Banco Fator S.A - 265"),
            '224' => i::__("Banco Fibra S.A - 224"),
            '626' => i::__("Banco Ficsa S.A - 626"),
            '94'  => i::__("Banco Finaxis - 94"),
            '612' => i::__("Banco Guanabara S.A - 612"),
            '12'  => i::__("Banco Inbursa - 12"),
            '604' => i::__("Banco Industrial Do Brasil S.A - 604"),
            '653' => i::__("Banco Indusval S.A - 653"),
            '77'  => i::__("Banco Inter S.A - 77"),
            '630' => i::__("Banco Intercap S.A - 630"),
            '249' => i::__("Banco Investcred Unibanco S.A - 249"),
            '184' => i::__("Banco Itaú Bba S.A - 184"),
            '29'  => i::__("Banco Itaú Consignado S.A - 29"),
            '479' => i::__("Banco Itaubank S.A - 479"),
            '376' => i::__("Banco J.P. Morgan S.A - 376"),
            '217' => i::__("Banco John Deere S.A - 217"),
            '76'  => i::__("Banco Kdb Brasil S.A. - 76"),
            '757' => i::__("Banco Keb Hana Do Brasil S.A - 757"),
            '300' => i::__("Banco La Nacion Argentina - 300"),
            '600' => i::__("Banco Luso Brasileiro S.A - 600"),
            '243' => i::__("Banco Máxima S.A - 243"),
            '389' => i::__("Banco Mercantil Do Brasil S.A - 389"),
            '389' => i::__("Banco Mercantil Do Brasil S.A. - 389"),
            '370' => i::__("Banco Mizuho S.A - 370"),
            '746' => i::__("Banco Modal S.A - 746"),
            '66'  => i::__("Banco Morgan Stanley S.A - 66"),
            '456' => i::__("Banco Mufg Brasil S.A - 456"),
            '169' => i::__("Banco Olé Bonsucesso Consignado S.A - 169"),
            '111' => i::__("Banco Oliveira Trust Dtvm S.A - 111"),
            '79'  => i::__("Banco Original Do Agronegócio S.A - 79"),
            '712' => i::__("Banco Ourinvest S.A - 712"),
            '623' => i::__("Banco Pan - 623"),
            '611' => i::__("Banco Paulista - 611"),
            '643' => i::__("Banco Pine S.A - 643"),
            '747' => i::__("Banco Rabobank Internacional Do Brasil S.A - 747"),
            '633' => i::__("Banco Rendimento S.A - 633"),
            '494' => i::__("Banco Rep Oriental Uruguay - 494"),
            '741' => i::__("Banco Ribeirão Preto - 741"),
            '120' => i::__("Banco Rodobens S.A - 120"),
            '743' => i::__("Banco Semear S.A - 743"),
            '754' => i::__("Banco Sistema - 754"),
            '366' => i::__("Banco Societe Generale Brasil - 366"),
            '637' => i::__("Banco Sofisa S.A (Sofisa Direto) - 637"),
            '464' => i::__("Banco Sumitomo Mitsui Brasil S.A - 464"),
            '82'  => i::__("Banco Topázio S.A - 82"),
            '634' => i::__("Banco Triangulo S.A (Banco Triângulo) - 634"),
            '18'  => i::__("Banco Tricury S.A - 18"),
            '655' => i::__("Banco Votorantim S.A - 655"),
            '610' => i::__("Banco Vr S.A - 610"),
            '119' => i::__("Banco Western Union - 119"),
            '124' => i::__("Banco Woori Bank Do Brasil S.A - 124"),
            '348' => i::__("Banco Xp S/A - 348"),
            '756' => i::__("Banco (Banco Cooperativo Do Brasil) - 756"),
            '21'  => i::__("Banco Banestes S.A - 21"),
            '41'  => i::__("Banrisul – Banco Do Estado Do Rio Grande Do Sul S.A - 41"),
            '268' => i::__("Barigui Ch - 268"),
            '81'  => i::__("Bbn Banco Brasileiro De Negocios S.A - 81"),
            '75'  => i::__("Bco Abn Amro S.A - 75"),
            '213' => i::__("Bco Arbi S.A - 213"),
            '24'  => i::__("Bco Bandepe S.A - 24"),
            '74'  => i::__("Bco. J.Safra S.A - 74"),
            '144' => i::__("Bexs Banco De Cambio S.A. - 144"),
            '253' => i::__("Bexs Cc S.A - 253"),
            '134' => i::__("Bgc Liquidez Dtvm Ltda - 134"),
            '752' => i::__("Bnp Paribas Brasil S.A - 752"),
            '17'  => i::__("Bny Mellon Banco S.A - 17"),
            '755' => i::__("Bofa Merrill Lynch Bm S.A - 755"),
            '301' => i::__("Bpp Instituição De Pagamentos S.A - 301"),
            '126' => i::__("Br Partners Bi - 126"),
            '125' => i::__("Brasil Plural S.A Banco - 125"),
            '92'  => i::__("Brk S.A - 92"),
            '173' => i::__("Brl Trust Dtvm Sa - 173"),
            '142' => i::__("Broker Brasil Cc Ltda - 142"),
            '292' => i::__("Bs2 Distribuidora De Títulos E Investimentos - 292"),
            '11'  => i::__("C.Suisse Hedging-Griffo Cv S.A (Credit Suisse) - 11"),
            '288' => i::__("Carol Dtvm Ltda - 288"),
            '130' => i::__("Caruana Scfi - 130"),
            '159' => i::__("Casa Credito S.A - 159"),
            '97'  => i::__("Ccc Noroeste Brasileiro Ltda - 97"),
            '16'  => i::__("Ccm Desp Trâns Sc E Rs - 16"),
            '286' => i::__("Ccr De Ouro - 286"),
            '279' => i::__("Ccr De Primavera Do Leste - 279"),
            '273' => i::__("Ccr De São Miguel Do Oeste - 273"),
            '89'  => i::__("Ccr Reg Mogiana - 89"),
            '114' => i::__("Central Cooperativa De Crédito No Estado Do Espírito Santo - 114"),
            '477' => i::__("Citibank N.A - 477"),
            '180' => i::__("Cm Capital Markets Cctvm Ltda - 180"),
            '127' => i::__("Codepe Cvc S.A - 127"),
            '163' => i::__("Commerzbank Brasil S.A Banco Múltiplo - 163"),
            '60'  => i::__("Confidence Cc S.A - 60"),
            '85'  => i::__("Coop Central Ailos - 85"),
            '98'  => i::__("Credialiança Ccr - 98"),
            '10'  => i::__("Credicoamo - 10"),
            '133' => i::__("Cresol Confederação - 133"),
            '182' => i::__("Dacasa Financeira S/A - 182"),
            '487' => i::__("Deutsche Bank S.A Banco Alemão - 487"),
            '140' => i::__("Easynvest – Título Cv S.A - 140"),
            '149' => i::__("Facta S.A. Cfi - 149"),
            '285' => i::__("Frente Cc Ltda - 285"),
            '278' => i::__("Genial Investimentos Cvm S.A - 278"),
            '138' => i::__("Get Money Cc Ltda - 138"),
            '64'  => i::__("Goldman Sachs Do Brasil Bm S.A - 64"),
            '177' => i::__("Guide - 177"),
            '146' => i::__("Guitta Cc Ltda - 146"),
            '78'  => i::__("Haitong Bi Do Brasil S.A - 78"),
            '62'  => i::__("Hipercard Bm S.A - 62"),
            '189' => i::__("Hs Financeira - 189"),
            '269' => i::__("Hsbc Banco De Investimento - 269"),
            '271' => i::__("Ib Cctvm Ltda - 271"),
            '157' => i::__("Icap Do Brasil Ctvm Ltda - 157"),
            '132' => i::__("Icbc Do Brasil Bm S.A - 132"),
            '492' => i::__("Ing Bank N.V - 492"),
            '139' => i::__("Intesa Sanpaolo Brasil S.A - 139"),
            '652' => i::__("Itaú Unibanco Holding Bm S.A - 652"),
            '488' => i::__("Jpmorgan Chase Bank - 488"),
            '399' => i::__("Kirton Bank - 399"),
            '495' => i::__("La Provincia Buenos Aires Banco - 495"),
            '293' => i::__("Lastro Rdv Dtvm Ltda - 293"),
            '105' => i::__("Lecca Cfi S.A - 105"),
            '145' => i::__("Levycam Ccv Ltda - 145"),
            '113' => i::__("Magliano S.A - 113"),
            '128' => i::__("Ms Bank S.A Banco De Câmbio - 128"),
            '137' => i::__("Multimoney Cc Ltda - 137"),
            '14'  => i::__("Natixis Brasil S.A - 14"),
            '655' => i::__("Neon Pagamentos S.A (Mesmo Código Do Banco Votorantim) - 655"),
            '237' => i::__("Next Bank (Mesmo Código Do Bradesco) - 237"),
            '191' => i::__("Nova Futura Ctvm Ltda - 191"),
            '753' => i::__("Novo Banco Continental S.A Bm - 753"),
            '613' => i::__("Omni Banco S.A - 613"),
            '254' => i::__("Parana Banco S.A - 254"),
            '194' => i::__("Parmetal Dtvm Ltda - 194"),
            '174' => i::__("Pernambucanas Financ S.A - 174"),
            '100' => i::__("Planner Corretora De Valores S.A - 100"),
            '93'  => i::__("Pólocred Scmepp Ltda - 93"),
            '108' => i::__("Portocred S.A - 108"),
            '283' => i::__("Rb Capital Investimentos Dtvm Ltda - 283"),
            '101' => i::__("Renascenca Dtvm Ltda - 101"),
            '270' => i::__("Sagitur Cc Ltda - 270"),
            '751' => i::__("Scotiabank Brasil - 751"),
            '276' => i::__("Senff S.A - 276"),
            '545' => i::__("Senso Ccvm S.A - 545"),
            '190' => i::__("Servicoop - 190"),
            '748' => i::__("Sicredi S.A - 748"),
            '183' => i::__("Socred S.A - 183"),
            '118' => i::__("Standard Chartered Bi S.A - 118"),
            '197' => i::__("Stone Pagamentos S.A - 197"),
            '340' => i::__("Super Pagamentos S/A (Superdital) - 340"),
            '143' => i::__("Treviso Cc S.A - 143"),
            '131' => i::__("Tullett Prebon Brasil Cvc Ltda - 131"),
            '129' => i::__("Ubs Brasil Bi S.A - 129"),
            '15'  => i::__("Ubs Brasil Cctvm S.A - 15"),
            '91'  => i::__("Unicred Central Rs - 91"),
            '136' => i::__("Unicred Cooperativa - 136"),
            '99'  => i::__("Uniprime Central Ccc Ltda - 99"),
            '84'  => i::__("Uniprime Norte Do Paraná - 84"),
            '298' => i::__("Vips Cc Ltda - 298"),
            '310' => i::__("Vortx Dtvm Ltda - 310"),
            '102' => i::__("Xp Investimentos S.A - 102"),
        ],
        'validations' => [
            'required' => i::__("O banco obrigatório")
        ]
    ],

    'payment_branch' =>  [
        'label' => i::__('Agência sem o dígito'),
        'type' => 'string',
        'validations' => [
            'required' => i::__("O agência obrigatório")
        ]

    ],
    'payment_branch_dv' =>  [
        'label' => i::__('Dígito verificador da agência'),
        'type' => 'string',
        'field_type' => 'fieldMask',
        'validations' => [
            'required' => i::__("O dígito verificador da agência obrigatório")
        ]
    ],
    'payment_account' =>  [
        'label' => i::__('Conta sem o dígito'),
        'type' => 'string',
        'validations' => [
            'required' => i::__("A conta obrigatória")
        ]
    ],
    'payment_account_dv' =>  [
        'label' => i::__('Dígito verificador da conta'),
        'type' => 'string',
        'field_type' => 'fieldMask',
        'validations' => [
            'required' => i::__("O Dígito verificador da conta obrigatória")
        ]
    ],
    'payment_sent_timestamp' =>  [
        'label' => i::__('Data de envio dos dados de pagamento'),
        'type' => 'string',
        'serialize' => function ($value) {
            if ($value) {
                return (new DateTime('now'))->format('Y-m-d H:i:s');
            }
        },
        'unserialize' => function ($value) {
            if ($value) {
                return (new DateTime($value))->format('Y-m-d H:i:s');
            }
        }
    ]
];
